lithops:
  backend: aws_lambda
  storage: aws_s3
  log_level: INFO
aws:
  region: "eu-central-1"
aws_lambda:
  execution_role: "arn:aws:iam::905418285725:role/lambdaLithopsExecutionRole"
  region: eu-central-1
  runtime: 905418285725.dkr.ecr.eu-central-1.amazonaws.com/lithops_v361_4we5_ttc-dev/ttc-loaders-dev:latest
  architecture: x86_64
  namespace: ttc-dev
  max_workers: 300
aws_s3:
  region: "eu-central-1"
  storage_bucket: dev-ttc-lithops-euc1